services:
  healthy-api:
    build:
      context: ./Healthy
      dockerfile: Healthy.Api/Dockerfile
      target: runtime
    image: ghcr.io/phuong-practice-projects/healthy-system/healthy-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=healthy-db;Database=HealthyDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=true;
    # Remove volume mounts for production
    volumes: []
    # Only expose internal port
    ports: []
    depends_on:
      - healthy-db
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  healthy-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Standard"
    # Don't expose DB port externally in production
    ports: []
    volumes:
      - healthy-db-data:/var/opt/mssql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  healthy-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - healthy-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  healthy-db-data:
