version: '3.8'

services:
  # healthy-api:
  #   build:
  #     context: ./Healthy
  #     dockerfile: Healthy.Api/Dockerfile
  #     target: build  # Use build stage for development with hot reload
  #   env_file:
  #     - env.development
  #   volumes:
  #     # Mount source for live development
  #     - ./Healthy:/src
  #     - /src/Healthy.Api/bin
  #     - /src/Healthy.Api/obj
  #   command: ["dotnet", "run", "--project", "/src/Healthy.Api/Healthy.Api.csproj", "--urls", "http://+:8080"]
  #   ports:
  #     - "5001:8080"
  #   depends_on:
  #     - healthy-db
  #   networks:
  #     - healthy-network

  healthy-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Dev@Passw0rd123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - healthy-db-dev-data:/var/opt/mssql
    networks:
      - healthy-network

  # Redis for caching (optional)
  healthy-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - healthy-redis-dev-data:/data
    networks:
      - healthy-network
    command: redis-server --appendonly yes

networks:
  healthy-network:
    driver: bridge

volumes:
  healthy-db-dev-data:
    driver: local
  healthy-redis-dev-data:
    driver: local
