services:
  healthy-api:
    build:
      context: ./Healthy
      dockerfile: Healthy.Api/Dockerfile
      target: build
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - ConnectionStrings__DefaultConnection=Server=healthy-db,1433;Database=HealthyDB;User Id=sa;Password=Dev@Passw0rd123!;TrustServerCertificate=true;Encrypt=false
    volumes:
      - ./Healthy:/src
      - /src/Healthy.Api/bin
      - /src/Healthy.Api/obj
      - /src/Healthy.Application/bin
      - /src/Healthy.Application/obj
      - /src/Healthy.Domain/bin
      - /src/Healthy.Domain/obj
      - /src/Healthy.Infrastructure/bin
      - /src/Healthy.Infrastructure/obj
    working_dir: /src
    command: ["dotnet", "watch", "run", "--project", "Healthy.Api/Healthy.Api.csproj", "--urls", "http://+:8080", "--no-restore"]
    depends_on:
      - healthy-db
    restart: unless-stopped

  healthy-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Dev@Passw0rd123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - healthy-db-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  healthy-db-data:
 